### ISSUE TITLE
Vyper support

### ISSUE THREAD

**Issue by gustavo-grieco** [agroce/echidna-parade#11]
Slither is not working properly with vyper right now (it cannot parse its code properly), however we could still take advantage of echidna-parade to run several echidna workers with different configurations.

**Comment by agroce** [comment]
Handled by https://github.com/agroce/echidna-parade/commit/dc08076d1fff08164c1e2be49ee16cf6e2b7c8c1 -- also handles multi-abi pruning, as we discussed on Slack
