### ISSUE TITLE
Forced termination of instances is causing empty output files when the contracts are large

### ISSUE THREAD

**Issue by gustavo-grieco** [agroce/echidna-parade#12]
This should be optional:

https://github.com/agroce/echidna-parade/blob/master/echidna_parade/echidna_parade.py#L307-L316

**Comment by agroce** [comment]
This is just collecting new corpus files.  When would you not want that?  Not sure I understand...

**Comment by agroce** [comment]
Ok, you can now make the system wait for echidnas, as of https://github.com/agroce/echidna-parade/commit/4983d43f917d27b4f22ce54851718d87c360824d -- in pip as 0.1.3
