### ISSUE TITLE
Shuffle the type of mutations using `mutConsts`

### ISSUE THREAD

**Issue by gustavo-grieco** [agroce/echidna-parade#3]
Echidna allows to set different weights for each type of mutations

https://github.com/crytic/echidna/blob/3365aac222490d345726e8d079b07a47f8d7aa23/lib/Echidna/Mutator/Corpus.hs#L76-L94

using the `mutConsts` config value:

https://github.com/crytic/echidna/blob/3365aac222490d345726e8d079b07a47f8d7aa23/lib/Echidna/Config.hs#L133

In particular, I believe echidna-parade can be more effective if the use of `mutConst` is more "sparse" (have a lot of zeros).

**Comment by agroce** [comment]
Are those values 0/1, or are they 0-1 reals?
